name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

   
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Set up Firebase Admin SDK JSON
      run: |
        mkdir -p app  
        echo "${{ secrets.FIREBASE_ADMINSDK_JSON }}" | base64 --decode > ./busconncet-firebase-adminsdk-3q883-4a49b71c98.json
    
    - name: Run tests
      run: pytest --maxfail=3 --disable-warnings
      
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      

        
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/taipeibusconnect:latest

    - name: Push the Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/taipeibusconnect:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to EC2 using SSH
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          sudo docker-compose down
          sudo docker-compose pull
          sudo docker-compose up -d


